# Generated by Django 5.0.4 on 2024-04-07 07:14

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="product",
            name="tags",
        ),
        migrations.DeleteModel(
            name="Tags",
        ),
    ]
