# Generated by Django 5.0.4 on 2024-04-12 05:25

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0004_alter_product_category"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="date",
            field=models.DateTimeField(auto_now_add=True, null=True),
        ),
        migrations.AlterField(
            model_name="product",
            name="vendor",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="vendor",
                to="baseapp.vendor",
            ),
        ),
    ]
