# Generated by Django 5.0.4 on 2024-04-12 06:08

import baseapp.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("baseapp", "0005_vendor_date_alter_product_vendor"),
    ]

    operations = [
        migrations.AddField(
            model_name="vendor",
            name="cover_image",
            field=models.ImageField(
                default="cover_image.jpg", upload_to=baseapp.models.user_directory_path
            ),
        ),
    ]
